# Site settings
title: SciFly7 (Variocity)
email: scifly7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Science for flying. Flying for science.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scifly7.github.io" # the base hostname & protocol for your site
twitter_username: scifly7
github_username:  scifly7
# Build settings

markdown: kramdown

kramdown:
  math_engine: mathjax
